title: "My website"
author: "Davide Bolognini"
description: "Affiliation: Human Technopole"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "README.md", title: "About me"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:davidebolognini7@gmail.com"}
  - {title: Github, icon: square-github, url: "https://github.com/davidebolo1993"}
  - {title: X, icon: square-x-twitter, url: "https://x.com/davidebolo93"}
  - {title: Workplace, icon: dna, url: "https://humantechnopole.it/en/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
